In [19]:
import numpy as np
A = np.array([1, 2, 3, 4])
print(A)

[1 2 3 4]


In [20]:
np.ndim(A)

1

In [21]:
A.shape

(4,)

In [22]:
A.shape[0]

4

In [23]:
B = np.array([[1,2], [3,4], [5,6]])
print(B)

[[1 2]
 [3 4]
 [5 6]]


In [24]:
np.ndim(B)

2

In [25]:
B.shape

(3, 2)

In [26]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])
np.dot(A, B)

array([[19, 22],
       [43, 50]])